config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories
  resources :products
  resources :users
  resources :provinces
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"
  get "search", to: "search#index"
  get "cart", to: "products#cart"

  post 'products/add_to_cart/:id', to: 'products#add_to_cart', as: 'add_to_cart'
  delete 'products/remove_from_cart/:id', to: 'products#remove_from_cart', as: 'remove_from_cart'

  get "checkout", to: "products#checkout"
  get "success", to: "products#success"
  get "about", to: "products#about"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  validates :name, :brand, presence: true
  validates :price, numericality: true
  paginates_per 8
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :users

  validates :name, :tax_rate, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :province
  has_many :orders

  validates :first_name, :last_name, :address, :postal_code, :city, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_query
  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  def set_query
    @query = Product.ransack(params[:q])
  end

  def configure_devise_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address, :postal_code, :city, :province_id])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :postal_code, :city, :province_id])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html do
          redirect_to category_url(@category), notice: "Category was successfully created."
        end
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html do
          redirect_to category_url(@category), notice: "Category was successfully updated."
        end
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @order = Order.all
  end

  def create
    @order = Order.new(order_params)
  end

  def new
    @order = Order.new
  end

  private

  def order_params
    params.require(:order).permit(:id, :total)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]
  before_action :initialize_session
  before_action :load_cart

  # GET /products or /products.json
  def index
    @products = Product.page params[:page]
  end

  def add_to_cart
    id = params[:id].to_i
    session[:cart] << id
    redirect_to root_path
  end

  def remove_from_cart
    id = params[:id].to_i
    session[:cart].delete(id)
    redirect_to cart_path
  end

  # GET /products/1 or /products/1.json
  def show; end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html do
          redirect_to product_url(@product), notice: "Product was successfully created."
        end
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html do
          redirect_to product_url(@product), notice: "Product was successfully updated."
        end
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:brand, :name, :description, :price, :image)
  end

  def initialize_session
    session[:cart] ||= []
  end

  def load_cart
    @cart = Product.find(session[:cart])
  end
end

app/controllers/provinces_controller.rb
class ProvincesController < ApplicationController
  def province_params
    params.require(:province).permit(:id, :name, :tax_rate)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @query = Product.ransack(params[:q])
    @products = @query.result(distinct:true)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def user_params
    params.require(:user).permit(:email, :encrypted_password, :first_name, :last_name, :postal_code, :city, :address, :province_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def cart_total
    Product.where(id: @cart).sum(:price).round(2)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<div class="categories">
  <div id="<%= dom_id category %>">
    <p>
      <strong><%= category.name %></strong>
    </p>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<div class="categories">
  <h2>Categories</h2>

  <% @categories.order("name ASC").each do |category| %>
    <h5><%= link_to category.name, category %></h5>
  <% end %>
</div>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<div class="categories">
  <%= render @category %>
  <ul>
  <% @category.products.each do |product| %>
    <li><%= link_to product.name, product %></li>
  <% end %>
  </ul>

  <div>
    <%= link_to "Back to categories", categories_path %>
  </div>
  <br>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :brand, style: "display: block" %>
    <%= form.text_field :brand %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">

  <h3><%= product.name %></h3>

  <p>
    <strong>Brand:</strong>
    <%= product.brand.capitalize %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Price:</strong>
    $<%= product.price %>
  </p>

  <p>
    <%= image_tag product.image, alt: "Picture of the product.", style: 'max-width: 400px' %>
  </p>

</div>

app/views/products/about.html.erb
<div class="about">
  <h2>About Us</h2>
  <p>We are a small business located in Winnipeg, Manitoba!</p>
  <p>We do not have a lot of stock, so each product is limited to only 1 per customer.</p>
  <p>We currently only ship to locations within Canada but hope to expand internationally in the future.</p>
  <p>Shipping is free if you spend $50 before tax.</p>
  <p>Thanks for shopping with us!</p>
</div>

app/views/products/cart.html.erb
<div class="cart">
  <h2>Shopping Cart - Subtotal: $<%= cart_total %></h2>
  <% unless cart_total >= 50 %>
    <h5><span>Spend another $<%= (50 - cart_total).round(2) %> for free shipping!</span></h5>
  <% end %>
  <% if @cart.empty? %>
      <p>No items in cart.</p>
  <% else %>
    <ul>
      <% @cart.each do |product| %>
        <li><%= link_to product.name %> - $<%= product.price %></li>
        <li><%= image_tag product.image, alt: "Image of a product." %></li>
        <li><%= button_to 'Remove From Cart', remove_from_cart_path(product), method: :delete %></li>
        <li>&nbsp;</li>
      <% end %>
    </ul>
  <% end %>
  <div class="checkoutLink">
  <% if user_signed_in? && !@cart.empty? %>
    <%= link_to "Checkout!", checkout_path %>
  <% elsif user_signed_in? && @cart.empty? %>
  <% else %>
    <%= link_to "Please Log In to Checkout", new_user_session_path %>
  <% end %>
  </div>
</div>


app/views/products/checkout.html.erb
<div class="checkoutForm">
  <h1>Checkout!</h1>
  <h5>Subtotal: $<%= cart_total %></h5>
  <h5>Sales Tax: $<%= (current_user.province.tax_rate * cart_total).round(2) %></h5>
  <% if cart_total >= 50 %>
    <h5>Shipping: Free!</h5>
    <h4>Total: $<%= ((current_user.province.tax_rate * cart_total) + cart_total).round(2) %></h4>
  <% else %>
    <h5>Shipping: $9.99</h5>
    <h4>Total: $<%= ((current_user.province.tax_rate * cart_total) + cart_total + 9.99).round(2) %></h4>
  <% end %>
  <p>----------------------------</p>
  <h4>Shipping Information:</h4>
  <p>Name: <%= current_user.first_name %> <%= current_user.last_name %></p>
  <p>Address: <%= current_user.address %></p>
  <p>Postal Code: <%= current_user.postal_code %></p>
  <p>City: <%= current_user.city %></p>
  <p>Province: <%= current_user.province.name %></p>
  <p>----------------------------</p>
</div>
<div class="cardPayment">
  <h4>Payment Method:</h4>
  <%= form_tag( { :action => "success", }, { :method => :get }) do %>
    <%= radio_button(:card, "card", "Visa", :required => true) %> Visa&nbsp;&nbsp;
    <%= radio_button(:card, "card", "Mastercard") %> Mastercard&nbsp;&nbsp;
    <%= radio_button(:card, "card", "American Express") %> American Express
    <br>
    <br>
    <%= label_tag "name" %><br>
    <%= text_field :name, "name", :required => true %><br>

    <%= label_tag "card_number_(no_spaces)" %><br>
    <%= text_field :card_number, "card_number", :required => true, :maxlength => 16, :pattern => "^[0-9]{15}(?:[0-9]{1})?$" %><br>

    <div class="expiration">
      <div class="expirationDate">
        <%= label_tag "expiration" %><br>
        <%= date_select :expiration, "expiration", start_year: 2023, order: [:month, :year] %>
      </div>
      <div class="securityCode">
        <%= label_tag "security_code" %>
        <%= text_field :security_code, "security_code", :required => true, :maxlength => 3, :pattern => "[0-9][0-9][0-9]" %>
      </div>

      <div class="actions">
      <%= submit_tag "Purchase" %>
      </div>
    </div>
  <% end %>
</div>
<div class="checkoutCancel">
  <%= link_to "Go Back to Cart", cart_path, method: :get %>
</div>




app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<div class="products">
  <h2>Products</h2>

  <% @products.order("brand ASC").each do |product| %>
    <h5><%= product.name %></h5>
    <p>$<%= product.price %></p>
    <%= image_tag product.image, style: 'max-width: 200px', alt: "Image of a product." %>
    <p><%= link_to "View Product", product %></p>
  <% end %>
</div>
<div class="paginate">
  <%= paginate @products %>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<div class="products">
  <%= render @product %>

  <% if @cart.include?(@product) %>
    <%= button_to 'Remove From Cart', remove_from_cart_path(@product), method: :delete %>
  <% else %>
    <%= button_to 'Add to Cart', add_to_cart_path(@product), method: :post %>
  <% end %>
  <br>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/success.html.erb
<div class="invoice">
  <h1>Order Confirmed!</h1>
  <div class=invoiceBorder>
    <h4>Shipping To:</h4>
    <p><%= current_user.first_name %> <%= current_user.last_name %></p>
    <p><%= current_user.address %></p>
    <p><%= current_user.postal_code %></p>
    <p><%= current_user.city %>, <%= current_user.province.name %></p>
    <h4>Items:</h4>
    <ol>
      <% @cart.each do |product| %>
        <li><%= product.name %> - $<%= product.price %></li>
      <% end %>
    </ol>
    <p>-----------------------</p>
    <h5>Subtotal: $<%= cart_total %></h5>
    <h5>Sales Tax: $<%= (current_user.province.tax_rate * cart_total).round(2) %></h5>
    <% if cart_total >= 50 %>
      <h5>Shipping: Free!</h5>
      <h4>Total: $<%= ((current_user.province.tax_rate * cart_total) + cart_total).round(2) %></h4>
    <% else %>
      <h5>Shipping: $9.99</h5>
      <h4>Total: $<%= ((current_user.province.tax_rate * cart_total) + cart_total + 9.99).round(2) %></h4>
    <% end %>

  </div>
  <div class="backButton">
    <%= button_to "Back to Site", destroy_user_session_path, method: :delete %>
  </div>
</div>

app/views/search/_form.html.erb
<%= search_form_for(@query, url: search_path, method: :get, class:'d-flex') do |f| %>
    <%= f.search_field :brand_or_name_i_cont_any, placeholder: "Search..." %>
    <%= f.submit "Search", class:"btn btn-outline-info" %>
<% end %>

app/views/search/index.html.erb
<br>
<div class="results">
  <h4><%= pluralize(@products.count, "Result") %></h4>
</div>
  <br>
<div class="container">
  <table class="table table-light table-striped">
    <thead>
      <tr>
        <th><%= sort_link(@query, :brand, "Brand", default_order: :asc)%></th>
        <th><%= sort_link(@query, :name, "Name", default_order: :asc)%></th>
        <th><%= sort_link(@query, :price, "Price", default_order: :asc)%></th>
      </tr>
    </thead>
    <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.brand %></td>
        <td><%= link_to product.name, product %></td>
        <td>$<%= product.price %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>