config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories
  resources :products
  resources :users
  resources :provinces
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"
  get "search", to: "search#index"
  get "cart", to: "products#cart"

  post 'products/add_to_cart/:id', to: 'products#add_to_cart', as: 'add_to_cart'
  delete 'products/remove_from_cart/:id', to: 'products#remove_from_cart', as: 'remove_from_cart'

  get "checkout", to: "products#checkout"
  get "success", to: "products#success"
  get "about", to: "products#about"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  validates :name, :brand, presence: true
  validates :price, numericality: true
  paginates_per 8
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :users

  validates :name, :tax_rate, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :province
  has_many :orders

  validates :first_name, :last_name, :address, :postal_code, :city, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html do
          redirect_to category_url(@category), notice: "Category was successfully created."
        end
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html do
          redirect_to category_url(@category), notice: "Category was successfully updated."
        end
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @order = Order.all
  end

  def create
    @order = Order.new(order_params)
  end

  def new
    @order = Order.new
  end

  private

  def order_params
    params.require(:order).permit(:id, :total)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]
  before_action :initialize_session
  before_action :load_cart

  # GET /products or /products.json
  def index
    @products = Product.page params[:page]
  end

  def add_to_cart
    id = params[:id].to_i
    session[:cart] << id
    redirect_to root_path
  end

  def remove_from_cart
    id = params[:id].to_i
    session[:cart].delete(id)
    redirect_to cart_path
  end

  # GET /products/1 or /products/1.json
  def show; end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html do
          redirect_to product_url(@product), notice: "Product was successfully created."
        end
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html do
          redirect_to product_url(@product), notice: "Product was successfully updated."
        end
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:brand, :name, :description, :price, :image)
  end

  def initialize_session
    session[:cart] ||= []
  end

  def load_cart
    @cart = Product.find(session[:cart])
  end
end

app/controllers/provinces_controller.rb
class ProvincesController < ApplicationController
  def province_params
    params.require(:province).permit(:id, :name, :tax_rate)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @query = Product.ransack(params[:q])
    @products = @query.result(distinct:true)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def user_params
    params.require(:user).permit(:email, :encrypted_password, :first_name, :last_name, :postal_code, :city, :address, :province_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def cart_total
    Product.where(id: @cart).sum(:price).round(2)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #ffdfe8;">
  <div class="container-fluid">
    <h2 class="navbar-text">Trendify</h2><br>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <span class="navbar-text"><%= link_to "Products", products_path %></span>
        </li>
        <li class="nav-item">
          <span class="navbar-text"><%= link_to "Categories", categories_path %></span>
        </li>
        <li class="nav-item">
          <span class="navbar-text"><%= link_to "About Us", about_path %></span>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <span class="navbar-text">Welcome, <%= current_user.first_name %>!</span>
          </li>
          <li class="nav-item">
            <span class="navbar-text"><%= link_to "Edit Account", edit_user_registration_path %></span>
          </li>
        <% else %>
          <li class="nav-item">
            <span class="navbar-text"><%= link_to "Log In", new_user_session_path %></span>
          </li>
        <% end %>
        <li class="nav-item">
          <span class="navbar-text"><%= link_to "Shopping Cart", cart_path %></span>
        </li>
            <li><%= link_to "Admin Dashboard", admin_dashboard_path %></li>
      </ul>
      <%= render "search/form" %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trendify</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% unless action_name == "success" %>
    <%= render "layouts/navbar" %>
    <% if user_signed_in? %>
      <div class="logOutButton">
        <%= button_to "Log Out", destroy_user_session_path, method: :delete %>
      </div>
    <% end %>
  <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>